### PR TITLE
Default to HTTP 412 for capture_errors_json, allow custom status

### PR DESCRIPTION
**Pull request by fasterthanlime**
For your consideration :)

There's probably a better way to do it, but I've used a similar approach with success you-know-elsewhere.

HTTP codes are important! :+1:

### CODE REVIEW

**Comment by lordnynex** [comment]
Just wanted to throw my two cents in. I like the idea of this patch but merging this would break quite a bit of my code where I've had to do this on my own. If this could be done without modifying capture_errors_json in such a significant way.

The hard coded response code also does not adequately describe what the error is. 
```
10.4.13 412 Precondition Failed

   The precondition given in one or more of the request-header fields
   evaluated to false when it was tested on the server. This response
   code allows the client to place preconditions on the current resource
   metainformation (header field data) and thus prevent the requested
   method from being applied to a resource other than the one intended.
```

Some examples, 
- There are cases when I generate a 405 error thats caught by capture_errors_json to indicate the API method is not allowed. 
- There are 403 errors I throw that are caught by capture_errors_json to indicate the resource does not belong to the requester. 
- There are 400 errors I throw that are caught by capture_errors_json that indicate a PUT/POST method fails to meet the criteria of assert_valid.

This patch would do more harm than good. If there was a more abstract means of signaling error/error visibility/log or not log etc, then I'd say this patch is an awesome addition.

**Comment by fasterthanlime** [comment]
@lordnynex the whole ideas is that this patch allows you to specify the http status along with the error message, so that you can write the following:

```moonscript
assert_error some_condition, {403, "forbidden"}
```

I agree that the default of 412 doesn't adequately describe all possible errors, maybe 400 would be a better default, maybe not. In any case, the current default (200) is definitely wrong.

However, that is a breaking change for applications that rely on capture_errors_json always returning 200. Perhaps another function then?

**Comment by lordnynex** [comment]
Why modify capture_errors_json at all? Why not call render_errors_json from handle_error if the user decides to?

**Comment by fasterthanlime** [comment]
> Why modify capture_errors_json at all? Why not call render_errors_json from handle_error if the user decides to?

Yes technically, people can still do whatever they want with capture_errors on their side — but what's the use in using a framework if it doesn't have sensible defaults? To me, capture_errors_json right now is wrong, because if there's an error, then the operation hasn't succeeded, and if it hasn't succeeded it certainly shouldn't be in the 2xx http code family.

Now, breaking updates are no fun, so maybe there's another way to to do that — but for everyone using lapis out there and having their server return HTTP 200 on failed API calls, well, that's just wrong. One shouldn't have to parse JSON & check the body for 'success' or the absence of 'errors' — what if the server didn't return JSON at all? Why should handling a 500 (error in the code for example) be any different than handling a 403, or a 404, as far as the client is concerned?

This PR is just for @leafo's consideration (and the community, too) — I have no doubt the end solution will be much better :)

**Comment by fasterthanlime** [comment]
Well, that's not happening

**Pull request closed without merging**
