### PR TITLE
Use luaossl's hmac module if available

### PR DESCRIPTION
**Pull request by daurnimator**

### CODE REVIEW

**Comment by leafo** [comment]
is there an advantage of this library over luacrypto. I've since added luacrypto to the rockspec, that check in the specs is not necessary.

Should the library choice be configurable?

**Comment by daurnimator** [comment]
I've got quite a low opinion of luacrypto and would prefer not to install it.
I didn't want to change the default, as this is just my personal opinion.
however I did want to make it an option.

**Comment by Guard13007** [comment]
@daurnimator Could you say why you have such a low opinion of it?

**Comment by daurnimator** [comment]
> @daurnimator Could you say why you have such a low opinion of it?

  - Not maintained (and lacking a current project owner)
  - Doesn't support lua 5.3
    Barely supports 5.2
  - Not safe in multithreaded environments
  - Lacking lots of features I'd like

**Comment by leafo** [comment]
I'm fine with changing the default, I'm not particularly tied to it. (assuming it doesn't break anything)

**Comment by daurnimator** [comment]
So are there modifications you want me to make to this pull request? Or is it good to merge?

**Comment by leafo** [comment]
I think we should pick one library, and not support the other.

**Comment by nonchip** [comment]
@leafo another reason maybe: luacrypto doesn't even build anymore if you have openssl 1.1

**Comment by nonchip** [comment]
@daurnimator you might wanna fix it in https://github.com/leafo/lapis/blob/master/lapis/spec/request.moon and https://github.com/leafo/lapis/blob/master/spec/session_spec.moon too btw

**Comment by daurnimator** [comment]
@nonchip fixed.

**Comment by leafo** [comment]
manually merged now, switched to luaossl by default

**Pull request closed without merging**
