### PR TITLE
mysql: lua-resty-mysql backend, models support, fix luasql backend, implement entity_exists

### PR DESCRIPTION
**Pull request by starius**
Changes:
 * lua-resty-mysql backend was implemented
 * luasql backend was fixed
   - forgotten argument password is now passed to method `connect`
   - returned number and boolean valued are converted from strings to Lua types
 * function `entity_exists` of module `mysql.schema` was implemented
 * support for models

Support for models:
 * modules "lapis.db" and "lapis.db.schema" select postgres or mysql based on the site's config
 * method Model.create did rely on RETURNING keyword to get ID of new rows. MySQL has no RETURNING keyword. I used a quick workaround:
   - if ID is already known (it is not autoincrement field), than variable "values" doesn't need any changing nothing needs to be changed in variable "values".
   - otherwise, ID is considered to be autoincrement field. The new row ID is provides by both mysql backends: luasql provides res.last_auto_id and lua-resty-mysql provides res.insert_id. Both of them are checked and used as value for the key `@primary_key` on success. This trick breaks code isolation between models and backends, so it needs some refactoring.

All the changes were tested with my project [kodomoquiz][kodomoquiz], which now supports mysql.

[kodomoquiz]: https://github.com/starius/kodomoquiz

see #46

### CODE REVIEW

**Comment by leafo** [comment]
nice, thanks.

model_spec.moon fails now because it requires `lapis.db.model`, which requires `lapis.db` and the test environment has no configuration unless it's explicitly been added.

```
Error → ./lapis/db/model.moon @ 2
./spec/model_spec.moon
./lapis/db/model.moon:2: You have to configure either postgres or mysql
```

I think we should probably create a model base class and and have the postgres and mysql versions extend from it. `lapis.db.model` would then use the same system you added to `lapis.db`

This way model spec can be updated to require the specific implementation of the model.

**Comment by leafo** [comment]
I fixed travis as well so you might want to rebase if you want it to run the tests on this branch

**Comment by lordnynex** [comment]
:+1:  for base model.

I'd love to get mongo/redis/cassandra 'providers' integrated. This is currently not possible because the current model class is strongly tied to postgres. :)

**Comment by starius** [comment]
Thank you for fixing travis! Current build [is failing](https://travis-ci.org/leafo/lapis/builds/57613950).

> I think we should probably create a model base class and and have the postgres and mysql versions extend from it.

:+1: 

1. What code creates and setups database when running tests? I can't find anything like "apt-get install postgres" and setup commands.
2. Should `spec/model_spec.moon` use postgres or mysql? What is the difference between `spec_postgres/model_spec.moon` and `spec/model_spec.moon`? I want to avoid code duplication in tests. Common code (models, asserts) should be moved to some module. Tests `spec_postgres/model_spec.moon` and `spec_mysql/model_spec.moon` should be thin modules, that set database to "postgres" or "mysql" and load this shared module.

**Comment by leafo** [comment]
There are three test folds, `spec` `spec_mysql` and `spec_postgres`. The `spec` directory has generic lapis tests, any of the model/db specs in there don't actually run queries on the database but instead generate SQL and an assertion checks to see if the result is the expected result.

I added `spec_mysql` and `spec_postgres` as I started writing specs that would require and actual server. There's nothing that automates starting the server. Travis currently doesn't run these specs. There are two makefile commands to set up the databases for each of these spec directories, `make test_db` for postgres, and `make mysq_test_db` for mysql. I do want to have these on travis I just haven't gotten an opportunity to set it up yet.

Regarding `spec/model_spec.moon`, currently that only tests query generation for postgres, since that's all there was. When we do this base class refactor I would just update that spec to test using the postgres model class first, just so it continues to test the stuff it originally tested. Afterwards we can figure out how to split things up and add mysql tests in there.

**Comment by starius** [comment]
Base class for models added

**Comment by leafo** [comment]
Sorry for the delay. It's merged now. I went through a made some refactors and pulled in the model specs from postgres into `spec_postgres`

I made `db` a parameter of the model now. Since in the tests there isn't a config, and the models were depending on requireing `lapis.db`, it was failing. Now the models can just reference `db` stored on self to get the correct version based on the database.

I renamed `lua_resty_mysql` to `resty_mysql`.

There was a bug with composite primary keys messing up autogen ids that I fixed.

I still haven't had a chance to fully test the `resty_mysql` backend, but I wanted to do some refactors back in master to make setting up test environments a bit easier. After I get that working, and tests written, I'll start updating the documentation.

Thanks for the patch!

**Pull request merged**
